# Generated by Django 4.2.4 on 2023-08-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_category_image_alter_category_title_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.CharField(default=1, max_length=60, verbose_name='Ürün Açıklaması / İçindekiler'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Ürün Fiyatı'),
            preserve_default=False,
        ),
    ]
