# Generated by Django 4.2.4 on 2023-08-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(default='fdgdf', max_length=60, verbose_name='Kategori İsmi (İngilizce)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='detail_en',
            field=models.CharField(default='gdfgd', max_length=60, verbose_name='Ürün Açıklaması / İçindekiler  (İngilizce)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(default='gfdgd', max_length=60, verbose_name='Ürün İsmi İngilizce'),
            preserve_default=False,
        ),
    ]
