# Generated by Django 4.2.4 on 2023-08-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_category_options_alter_sortablebook_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='category',
            name='my_order',
        ),
    ]
