# Generated by Django 4.2.4 on 2023-08-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_product_options_product_my_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Ürün Açıklaması / İçindekiler'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Ürün Açıklaması / İçindekiler  (İngilizce)'),
        ),
    ]
